### ISSUE TITLE
Bug: Révoquer les autorisations d'applications (Twitter API) -> Un problème est survenu

### ISSUE THREAD

**Issue by erikmd** [goulinkh/twittermastodon.com#1]
Merci @goulinkh d'avoir développé ce service !

Pour info : après avoir utilisé https://www.twittermastodon.com/,
il s'avère impossible de révoquer l'autorisation de twittermastodon.com du côté de Twitter, ça donne l'erreur suivante :

![2023-01-08_11-32-31_Screenshot_logout_issue](https://user-images.githubusercontent.com/10367254/211191471-ab8549f5-1e48-415c-bd71-4ee4f3f5eba4.png)

voir aussi https://twitter.com/ManiKhul/status/1597118302769532928

As-tu une idée de la source du problème ?

**Comment by goulinkh** [comment]
Bonjour Mr. Erik :) je viens d'essayer de révoquer les autorisations sur mon compte et cela marché, peut être que le problème était temporaire 🤔

**Comment by erikmd** [comment]
Bonjour Goulin ! :)
Malheureusement je viens de réussir à reproduire le souci ;
en revanche, pas sûr du tout que le problème soit lié à ton projet ! certainement juste un bug de l'API REST de Twitter…

**Comment by erikmd** [comment]
> certainement juste un bug de l'API REST de Twitter…

en effet : je viens de cliquer sur `Révoquer les autorisations d'applications` dans twitter.com (avec Firefox) et j'obtiens dans la console ↓
```
XHR POST https://api.twitter.com/2/oauth2/revoke_token_hash
    	
    HTTP/1.1 400 Bad Request
    …
    content-type: application/json;charset=UTF-8
    cache-control: no-cache, no-store, max-age=0
    content-length: 102
    x-frame-options: SAMEORIGIN
    content-encoding: gzip
    …
```

du coup, n'hésite pas à fermer cette issue puisque c'est un problème *upstream*…
